/* Generated By:JavaCC: Do not edit this line. LOGOConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LOGOConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORWARD = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int LEFT = 7;
  /** RegularExpression Id. */
  int REPEAT = 8;
  /** RegularExpression Id. */
  int PENUP = 9;
  /** RegularExpression Id. */
  int PENDOWN = 10;
  /** RegularExpression Id. */
  int CONSTANT = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<FORWARD>",
    "<RIGHT>",
    "<LEFT>",
    "\"REPEAT\"",
    "\"PENUP\"",
    "\"PENDOWN\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\".\"",
    "\"[\"",
    "\"]\"",
  };

}
